---
output: pdf_document
geometry: margin = 0cm
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(haven)
library(dplyr)
library(stargazer)
library(ggplot2)
library(patchwork)
theme_set(theme_classic())
```
```{r Prepare the data}
# Load the data
psid <- read_dta("20160995_PSID_regready_sept26.dta")

# Reeconding the sex variable and filter the dataset
psid_cp <- psid %>% 
  mutate(sex = ifelse(sex == 1, 1, sex),
         sex = ifelse(sex == 2, 0, sex)) %>%
  filter(farmer == 0, ft == 1, age >= 25 & age <= 64, annwks >= 26)

# Decrease all the year by 1 unit
psid_cp$wave <- psid_cp$wave - 1

# Create dataframes
# Variables list
human_dummy_variables <- c("ba", "adv", "northeast", "northcentral", "south", 
                           "white", "black", "hisp")
human_continuous_variables <- c("yrsftexpfz", "yrsptexpfz", "yrsftexpfzsq", 
                                "yrsptexpfzsq", "sch")
full_dummy_variables <- c("miningconstruction", "durables", 
                          "nondurables", "Transport", "Utilities", "Communications", 
                          "retailtrade", "wholesaletrade", "finance", "hotelsrestaurants", 
                          "Medical", "Education", "professional", "publicadmin",
                          "manager", "business", "financialop", "computer", "architect",
                          "scientist", "socialworker", "postseceduc", "legaleduc",
                          "artist", "lawyerphysician", "healthcare", "healthsupport",
                          "protective", "foodcare", "building", "sales", "officeadmin",
                          "constructextractinstall", "production",
                          "wtrgov",
                          "unjob")

# Dataframe
unadjusted_df <- psid_cp[, c("sex", "lnrealwg", "wave")]
human_df <- mutate(unadjusted_df, psid_cp[,c(human_dummy_variables, human_continuous_variables)])
full_df <- mutate(human_df, psid_cp[, full_dummy_variables])
```

```{r summary_statistics, results='asis'}

waves <- c(1980, 1998, 2010)

stargazer(as.data.frame(full_df[full_df$wave %in% waves, ]), 
          type = "latex", header = FALSE, title = "Summary Statistics for 1980, 1998, and 2010")

stargazer(as.data.frame(subset(full_df, wave == 2010)), type = "latex", header=FALSE, title = "Summary Statistics 2010")
stargazer(as.data.frame(subset(full_df, wave == 1998)), type = "latex", header=FALSE, title = "Summary Statistics 1998")
stargazer(as.data.frame(subset(full_df, wave == 1980)), type = "latex", header=FALSE, title = "Summary Statistics 1980")
```

```{r 2010table, results = "asis"}
lm1 <- lm(lnrealwg~.-wave, unadjusted_df, subset = (wave == 2010))
lm2 <- lm(lnrealwg~.-wave, human_df, subset = (wave == 2010))
lm3 <- lm(lnrealwg~.-wave, full_df, subset = (wave == 2010))
library(stargazer)
suppressWarnings({
stargazer(lm1, lm2, lm3, title = "Linear regression table for year 2010 ", type='latex', 
          single.row = TRUE, header = FALSE)})
```
```{r 1998 table, results = "asis"}
lm1 <- lm(lnrealwg~.-wave, unadjusted_df, subset = (wave == 1998))
lm2 <- lm(lnrealwg~.-wave, human_df, subset = (wave == 1998))
lm3 <- lm(lnrealwg~.-wave, full_df, subset = (wave == 1998))
library(stargazer)
suppressWarnings({
stargazer(lm1, lm2, lm3, title = "Linear regression table for year 1998 ", type='latex', 
          single.row = TRUE, header = FALSE)})
```
```{r 1980 table, results = "asis"}
lm1 <- lm(lnrealwg~.-wave, unadjusted_df, subset = (wave == 1980))
lm2 <- lm(lnrealwg~.-wave, human_df, subset = (wave == 1980))
lm3 <- lm(lnrealwg~.-wave, full_df, subset = (wave == 1980))
library(stargazer)
suppressWarnings({
stargazer(lm1, lm2, lm3, title = "Linear regression table for year 1980 ", type='latex', 
          single.row = TRUE, header = FALSE)})
```



